new step on ci for quality code control

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,10 +4,45 @@ on:
   push:
     branches:
       - main
+  pull_request:
+    branches:
+      - main
+
+jobs:
+  test-and-lint:
+    runs-on: ubuntu-latest
+    if: github.event_name == 'pull_request'
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '18'
+
+      - name: Install dependencies
+        run: npm install
+
+      - name: Run unit test
+        run: npm run dev
+
+      - name: Run linter
+        run: npm run lint
+
+      - name: Check package version
+        run: |
+          CURRENT_VERSION=$(jq -r '.version' package.json)
+          PREV_VERSION=$(git show HEAD~1:package.json | jq -r '.version')
+          if [ "$CURRENT_VERSION" = "$PREV_VERSION" ]; then
+            echo "ERROR: package.json version has NOT updated"
+            exit 1
+          fi
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
+    if: github.event_name == 'push'
 
     steps:
       - name: Checkout Front Repository
